In [1]:
import tensorflow as tf

In [6]:
a = 3 

w = tf.Variable([[0.5, 1.0]])
x = tf.Variable([[2.0], [1.0]])

y = tf.matmul(w, x)

# variables have to be explicitly initialized before you can run ops
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    print(y.eval())

[[2.]]


在tensorflow中最好用tf.float32的数据类型，可以避免出现各种奇怪的错误。

tensorflow的基本操作和numpy的差不多，只是细节上的差异。

In [10]:
# float32
tensor = tf.zeros([3,4],tf.int32)

with tf.Session() as sess:
    print(sess.run(tensor))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [13]:
# 'tensor' is [[1,2,3],[4,5,6]]
tensor = [[1,2,3], [4,5,6]]
tf.zeros_like(tensor) 
with tf.Session() as sess:
    print(sess.run(tf.zeros_like(tensor)))

[[0 0 0]
 [0 0 0]]


In [14]:
with tf.Session() as sess:
    print(sess.run(tf.ones_like(tensor)))

[[1 1 1]
 [1 1 1]]


In [16]:
# Constant 1-D Tensor populated with value list.
tensor = tf.constant([1,2,3,4,5,6,7])

# Constant 2-D tensor populated with scalar value -1.
tensor = tf.constant(-1.0, shape=[2,3])
with tf.Session() as sess:
    print(sess.run(tensor))

[[-1. -1. -1.]
 [-1. -1. -1.]]


In [17]:
lin = tf.linspace(10.0, 12.0, 3, name='linspace')

with tf.Session() as sess:
    print(sess.run(lin))

[10. 11. 12.]


In [18]:
start = 3
limit = 18
delta = 3
r = tf.range(start, limit, delta)

with tf.Session() as sess:
    print(sess.run(r))

[ 3  6  9 12 15]


In [19]:
norm = tf.random_normal([2,3], mean=-1, stddev=4)

# Shuffle the first dimension of a tensor
c = tf.constant([[1,2], [3,4], [5,6]])
shuff = tf.random_shuffle(c)

# Each time we run these ops, different results are generated
with tf.Session() as sess:
    print(sess.run(norm))
    print(sess.run(shuff))
    print(sess.run(shuff))

[[-8.170769   -2.2657852  -3.9377556 ]
 [ 0.06286657 -0.92650974 -3.0611207 ]]
[[1 2]
 [3 4]
 [5 6]]
[[5 6]
 [1 2]
 [3 4]]


for循环赋值，+=1在tensorflow中的操作

In [20]:
state = tf.Variable(0)
new_value = tf.add(state, tf.constant(1))
update = tf.assign(state, new_value)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(state))
    
    for _ in range(3):
        sess.run(update)
        print(sess.run(state))

0
1
2
3


tf.train.Saver tensorflow中模型的保存

In [24]:
w = tf.Variable([[0.5, 1.0]])
x = tf.Variable([[2.0], [1.0]])
y = tf.matmul(w, x)

init_op = tf.global_variables_initializer()

saver = tf.train.Saver()

with tf.Session() as sess:
    sess.run(init_op)
    
# Do some work with the model
# Save the variables to disk
    save_path = saver.save(sess, './models/lec01/lec01')
    print('Model saved in file:', save_path)
    

Model saved in file: ./models/lec01/lec01


将numpy的数据转换为tensor.  
tf.convert_to_tensor() 但不推荐这种使用方式。

In [25]:
import numpy as np
a = np.zeros((3,3))
ta = tf.convert_to_tensor(a)

with tf.Session() as sess:
    print(sess.run(ta))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


tf.placeholder()占位符的使用

In [27]:
input1 = tf.placeholder(tf.float32)
input2 = tf.placeholder(tf.float32)
output = tf.multiply(input1, input2)
with tf.Session() as sess:
    print(sess.run(output, feed_dict={input1:[7.], input2:[2.]}))

[14.]
