第一层版本：仅输入层和输出层

In [1]:
import os
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

# 载入数据集
mnist = input_data.read_data_sets(os.path.join(os.getcwd(), 'MNIST_data'), one_hot=True)

# 定义每个批次的大小
batch_size = 100
# 计算一共有多少个批次
n_batch = mnist.train.num_examples // batch_size  # 55000//100=550

# 定义两个placeholder
x = tf.placeholder(tf.float32, [None, 784])
y = tf.placeholder(tf.float32, [None, 10])

# 创建一个简单的神经网络
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))

prediction = tf.nn.softmax(tf.matmul(x, W) + b)

# 二次代价函数
loss = tf.reduce_mean(tf.square(prediction - y))
# 使用梯度下降法
train_step = tf.train.GradientDescentOptimizer(0.2).minimize(loss)

# 初始化变量
init = tf.global_variables_initializer()

# 结果存放在一个布尔型的列表中
# 正确与否的True or False的列表
# tf.argmax返回一维张量中最大的值所在的索引位置
correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(prediction, 1))

# 求准确率
# 通过tf.cast(x, dtype)将布尔型转换为浮点型
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(21):
        for batch in range(n_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            sess.run(train_step, feed_dict={x: batch_xs, y: batch_ys})
        
        acc = sess.run(accuracy,feed_dict={x:mnist.test.images,y:mnist.test.labels})
        print("Iter " + str(epoch) + ",Testing Accuracy " + str(acc))


Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/t10k-images-idx3-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Iter 0,Testing Accuracy 0.8323
Iter 1,Testing Accuracy 0.8708
Iter 2,Testing 

-----

### 优化空间：

- 神经网络结构
    - 隐层的神经元大小
    - 隐层数量
    - 激活函数
    
- 二次代价函数：
    - MSE
    - 交叉熵
    
- 迭代优化器：梯度下降法，最小二乘法，牛顿法，拟牛顿法
     - batch_size
     - learning_rate
     - epoches

下面主要调整了：
- 第一次调整：将二次代价函数改为了交叉熵代价函数
 >二次代价函数
 >loss = tf.reduce_mean(tf.square(prediction - y))
#### 使用交叉熵代价函数
> loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y, logits=prediction))

**注意：要使用tf.reduce_mean(）方法**

比较迭代的效果，使用交叉熵的结果收敛更快，效果更好。

In [10]:
import os
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

# 载入数据集
mnist = input_data.read_data_sets(os.path.join(os.getcwd(), 'MNIST_data'), one_hot=True)

# 定义每个批次的大小
batch_size = 100
# 计算一共有多少个批次
n_batch = mnist.train.num_examples // batch_size  # 55000//100=550

# 定义两个placeholder
x = tf.placeholder(tf.float32, [None, 784])
y = tf.placeholder(tf.float32, [None, 10])

# 创建一个简单的神经网络
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))

prediction = tf.nn.softmax(tf.matmul(x, W) + b)

# 二次代价函数
# loss = tf.reduce_mean(tf.square(prediction - y))

# 使用交叉熵代价函数
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=y, logits=prediction))
# 使用梯度下降法
train_step = tf.train.GradientDescentOptimizer(0.2).minimize(loss)

# 初始化变量
init = tf.global_variables_initializer()

# 结果存放在一个布尔型的列表中
# 正确与否的True or False的列表
# tf.argmax返回一维张量中最大的值所在的索引位置
correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(prediction, 1))

# 求准确率
# 通过tf.cast(x, dtype)将布尔型转换为浮点型
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(21):
        for batch in range(n_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            sess.run(train_step, feed_dict={x: batch_xs, y: batch_ys})
        
        acc = sess.run(accuracy,feed_dict={x:mnist.test.images,y:mnist.test.labels})
        print("Iter " + str(epoch) + ",Testing Accuracy " + str(acc))



Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/train-images-idx3-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/train-labels-idx1-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/t10k-images-idx3-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/t10k-labels-idx1-ubyte.gz
Iter 0,Testing Accuracy 0.8249
Iter 1,Testing Accuracy 0.8927
Iter 2,Testing Accuracy 0.9009
Iter 3,Testing Accuracy 0.9053
Iter 4,Testing Accuracy 0.9082
Iter 5,Testing Accuracy 0.9111
Iter 6,Testing Accuracy 0.9116
Iter 7,Testing Accuracy 0.9132
Iter 8,Testing Accuracy 0.9146
Iter 9,Testing Accuracy 0.9171
Iter 10,Testing Accuracy 0.9171
Iter 11,Testing Accuracy 0.9181
Iter 12,Testing Accuracy 0.9187
Iter 13,Testing Accuracy 0.9196
Iter 14,Testing Accuracy 0.9194
Iter 15,Testing Accuracy 0.9203
Iter 16,Testing Accuracy 0.9206
Iter 17,Testing Accuracy 0.9211
Iter 18,Testing 

---

修改batch_size，将其更改为50

In [11]:
import os
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

# 载入数据集
mnist = input_data.read_data_sets(os.path.join(os.getcwd(), 'MNIST_data'), one_hot=True)

# 定义每个批次的大小
batch_size = 50
# 计算一共有多少个批次
n_batch = mnist.train.num_examples // batch_size  # 55000//100=550

# 定义两个placeholder
x = tf.placeholder(tf.float32, [None, 784])
y = tf.placeholder(tf.float32, [None, 10])

# 创建一个简单的神经网络
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))

prediction = tf.nn.softmax(tf.matmul(x, W) + b)

# 二次代价函数
loss = tf.reduce_mean(tf.square(prediction - y))
# 使用梯度下降法
train_step = tf.train.GradientDescentOptimizer(0.2).minimize(loss)

# 初始化变量
init = tf.global_variables_initializer()

# 结果存放在一个布尔型的列表中
# 正确与否的True or False的列表
# tf.argmax返回一维张量中最大的值所在的索引位置
correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(prediction, 1))

# 求准确率
# 通过tf.cast(x, dtype)将布尔型转换为浮点型
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(21):
        for batch in range(n_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            sess.run(train_step, feed_dict={x: batch_xs, y: batch_ys})
        
        acc = sess.run(accuracy,feed_dict={x:mnist.test.images,y:mnist.test.labels})
        print("Iter " + str(epoch) + ",Testing Accuracy " + str(acc))



Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/train-images-idx3-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/train-labels-idx1-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/t10k-images-idx3-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/t10k-labels-idx1-ubyte.gz
Iter 0,Testing Accuracy 0.8711
Iter 1,Testing Accuracy 0.8877
Iter 2,Testing Accuracy 0.8962
Iter 3,Testing Accuracy 0.9015
Iter 4,Testing Accuracy 0.9055
Iter 5,Testing Accuracy 0.9069
Iter 6,Testing Accuracy 0.9089
Iter 7,Testing Accuracy 0.9105
Iter 8,Testing Accuracy 0.9124
Iter 9,Testing Accuracy 0.914
Iter 10,Testing Accuracy 0.9138
Iter 11,Testing Accuracy 0.9156
Iter 12,Testing Accuracy 0.9165
Iter 13,Testing Accuracy 0.9175
Iter 14,Testing Accuracy 0.9181
Iter 15,Testing Accuracy 0.9179
Iter 16,Testing Accuracy 0.9186
Iter 17,Testing Accuracy 0.9181
Iter 18,Testing A

---

将batch_size从100改成50，loss函数使用交叉熵。

In [12]:
import os
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

# 载入数据集
mnist = input_data.read_data_sets(os.path.join(os.getcwd(), 'MNIST_data'), one_hot=True)

# 定义每个批次的大小
batch_size = 50
# 计算一共有多少个批次
n_batch = mnist.train.num_examples // batch_size  # 55000//100=550

# 定义两个placeholder
x = tf.placeholder(tf.float32, [None, 784])
y = tf.placeholder(tf.float32, [None, 10])

# 创建一个简单的神经网络
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))

prediction = tf.nn.softmax(tf.matmul(x, W) + b)

# 二次代价函数
# loss = tf.reduce_mean(tf.square(prediction - y))

# 使用交叉熵代价函数
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=y, logits=prediction))
# 使用梯度下降法
train_step = tf.train.GradientDescentOptimizer(0.2).minimize(loss)

# 初始化变量
init = tf.global_variables_initializer()

# 结果存放在一个布尔型的列表中
# 正确与否的True or False的列表
# tf.argmax返回一维张量中最大的值所在的索引位置
correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(prediction, 1))

# 求准确率
# 通过tf.cast(x, dtype)将布尔型转换为浮点型
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(21):
        for batch in range(n_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            sess.run(train_step, feed_dict={x: batch_xs, y: batch_ys})
        
        acc = sess.run(accuracy,feed_dict={x:mnist.test.images,y:mnist.test.labels})
        print("Iter " + str(epoch) + ",Testing Accuracy " + str(acc))




Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/train-images-idx3-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/train-labels-idx1-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/t10k-images-idx3-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/t10k-labels-idx1-ubyte.gz
Iter 0,Testing Accuracy 0.8798
Iter 1,Testing Accuracy 0.9046
Iter 2,Testing Accuracy 0.9106
Iter 3,Testing Accuracy 0.914
Iter 4,Testing Accuracy 0.9155
Iter 5,Testing Accuracy 0.9188
Iter 6,Testing Accuracy 0.9168
Iter 7,Testing Accuracy 0.92
Iter 8,Testing Accuracy 0.9204
Iter 9,Testing Accuracy 0.9214
Iter 10,Testing Accuracy 0.9223
Iter 11,Testing Accuracy 0.9227
Iter 12,Testing Accuracy 0.9225
Iter 13,Testing Accuracy 0.9229
Iter 14,Testing Accuracy 0.924
Iter 15,Testing Accuracy 0.9239
Iter 16,Testing Accuracy 0.925
Iter 17,Testing Accuracy 0.9246
Iter 18,Testing Accur

-----

将batch_size从100改成50，loss函数使用交叉熵，并增加迭代次数，迭代次数从20到200.

In [14]:
import os
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

# 载入数据集
mnist = input_data.read_data_sets(os.path.join(os.getcwd(), 'MNIST_data'), one_hot=True)

# 定义每个批次的大小
batch_size = 50
# 计算一共有多少个批次
n_batch = mnist.train.num_examples // batch_size  # 55000//100=550

# 定义两个placeholder
x = tf.placeholder(tf.float32, [None, 784])
y = tf.placeholder(tf.float32, [None, 10])

# 创建一个简单的神经网络
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))

prediction = tf.nn.softmax(tf.matmul(x, W) + b)

# 二次代价函数
# loss = tf.reduce_mean(tf.square(prediction - y))

# 使用交叉熵代价函数
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=y, logits=prediction))
# 使用梯度下降法
train_step = tf.train.GradientDescentOptimizer(0.2).minimize(loss)

# 初始化变量
init = tf.global_variables_initializer()

# 结果存放在一个布尔型的列表中
# 正确与否的True or False的列表
# tf.argmax返回一维张量中最大的值所在的索引位置
correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(prediction, 1))

# 求准确率
# 通过tf.cast(x, dtype)将布尔型转换为浮点型
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(201):
        for batch in range(n_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            sess.run(train_step, feed_dict={x: batch_xs, y: batch_ys})
        if epoch % 50 == 0:
            acc = sess.run(accuracy,feed_dict={x:mnist.test.images,y:mnist.test.labels})
            print("Iter " + str(epoch) + ",Testing Accuracy " + str(acc))





Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/train-images-idx3-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/train-labels-idx1-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/t10k-images-idx3-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/t10k-labels-idx1-ubyte.gz
Iter 0,Testing Accuracy 0.8881
Iter 50,Testing Accuracy 0.9283
Iter 100,Testing Accuracy 0.9301
Iter 150,Testing Accuracy 0.929
Iter 200,Testing Accuracy 0.9302


-----

将batch_size从100改成50，loss函数使用交叉熵，并增加迭代次数，迭代次数从20到200.
+ 调整W和b的参数初始化方式

In [16]:
import os
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

# 载入数据集
mnist = input_data.read_data_sets(os.path.join(os.getcwd(), 'MNIST_data'), one_hot=True)

# 定义每个批次的大小
batch_size = 50
# 计算一共有多少个批次
n_batch = mnist.train.num_examples // batch_size  # 55000//100=550

# 定义两个placeholder
x = tf.placeholder(tf.float32, [None, 784])
y = tf.placeholder(tf.float32, [None, 10])

# 创建一个简单的神经网络
W = tf.Variable(tf.truncated_normal([784, 10]))
b = tf.Variable(tf.zeros([10]) + 0.1)

prediction = tf.nn.softmax(tf.matmul(x, W) + b)

# 二次代价函数
# loss = tf.reduce_mean(tf.square(prediction - y))

# 使用交叉熵代价函数
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=y, logits=prediction))
# 使用梯度下降法
train_step = tf.train.GradientDescentOptimizer(0.2).minimize(loss)

# 初始化变量
init = tf.global_variables_initializer()

# 结果存放在一个布尔型的列表中
# 正确与否的True or False的列表
# tf.argmax返回一维张量中最大的值所在的索引位置
correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(prediction, 1))

# 求准确率
# 通过tf.cast(x, dtype)将布尔型转换为浮点型
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(201):
        for batch in range(n_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            sess.run(train_step, feed_dict={x: batch_xs, y: batch_ys})
        if epoch % 50 == 0:
            acc = sess.run(accuracy,feed_dict={x:mnist.test.images,y:mnist.test.labels})
            print("Iter " + str(epoch) + ",Testing Accuracy " + str(acc))



Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/train-images-idx3-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/train-labels-idx1-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/t10k-images-idx3-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/t10k-labels-idx1-ubyte.gz
Iter 0,Testing Accuracy 0.4339
Iter 50,Testing Accuracy 0.913
Iter 100,Testing Accuracy 0.9199
Iter 150,Testing Accuracy 0.924
Iter 200,Testing Accuracy 0.9271


----

将batch_size从100改成50，loss函数使用交叉熵，并增加迭代次数，迭代次数从20到200.
+ 调整W和b的参数初始化方式
+ 添加一层隐藏层256个神经元，激活函数是tanh

In [17]:
import os
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

# 载入数据集
mnist = input_data.read_data_sets(os.path.join(os.getcwd(), 'MNIST_data'), one_hot=True)

# 定义每个批次的大小
batch_size = 50
# 计算一共有多少个批次
n_batch = mnist.train.num_examples // batch_size  # 55000//100=550

# 定义两个placeholder
x = tf.placeholder(tf.float32, [None, 784])
y = tf.placeholder(tf.float32, [None, 10])

# 创建一个简单的神经网络
W1 = tf.Variable(tf.truncated_normal([784, 256]))
b1 = tf.Variable(tf.zeros([256]) + 0.1)
L1_output = tf.nn.tanh(tf.matmul(x, W1) + b1)

W2 = tf.Variable(tf.truncated_normal([256, 10]))
b2 = tf.Variable(tf.zeros([10]) + 0.1)
prediction = tf.nn.softmax(tf.matmul(L1_output, W2) + b2)

# 二次代价函数
# loss = tf.reduce_mean(tf.square(prediction - y))

# 使用交叉熵代价函数
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=y, logits=prediction))
# 使用梯度下降法
train_step = tf.train.GradientDescentOptimizer(0.2).minimize(loss)

# 初始化变量
init = tf.global_variables_initializer()

# 结果存放在一个布尔型的列表中
# 正确与否的True or False的列表
# tf.argmax返回一维张量中最大的值所在的索引位置
correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(prediction, 1))

# 求准确率
# 通过tf.cast(x, dtype)将布尔型转换为浮点型
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(201):
        for batch in range(n_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            sess.run(train_step, feed_dict={x: batch_xs, y: batch_ys})
        if epoch % 50 == 0:
            acc = sess.run(accuracy,feed_dict={x:mnist.test.images,y:mnist.test.labels})
            print("Iter " + str(epoch) + ",Testing Accuracy " + str(acc))




Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/train-images-idx3-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/train-labels-idx1-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/t10k-images-idx3-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/t10k-labels-idx1-ubyte.gz
Iter 0,Testing Accuracy 0.5187
Iter 50,Testing Accuracy 0.9163
Iter 100,Testing Accuracy 0.9223
Iter 150,Testing Accuracy 0.9259
Iter 200,Testing Accuracy 0.9278


----

将batch_size从100改成50，loss函数使用交叉熵，并增加迭代次数，迭代次数从20到200.
+ 调整W和b的参数初始化方式
+ 添加一层隐藏层256个神经元，激活函数是tanh
+ 调整learning_rate为0.1

In [18]:
import os
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

# 载入数据集
mnist = input_data.read_data_sets(os.path.join(os.getcwd(), 'MNIST_data'), one_hot=True)

# 定义每个批次的大小
batch_size = 50
# 计算一共有多少个批次
n_batch = mnist.train.num_examples // batch_size  # 55000//100=550

# 定义两个placeholder
x = tf.placeholder(tf.float32, [None, 784])
y = tf.placeholder(tf.float32, [None, 10])

# 创建一个简单的神经网络
W1 = tf.Variable(tf.truncated_normal([784, 256]))
b1 = tf.Variable(tf.zeros([256]) + 0.1)
L1_output = tf.nn.tanh(tf.matmul(x, W1) + b1)

W2 = tf.Variable(tf.truncated_normal([256, 10]))
b2 = tf.Variable(tf.zeros([10]) + 0.1)
prediction = tf.nn.softmax(tf.matmul(L1_output, W2) + b2)

# 二次代价函数
# loss = tf.reduce_mean(tf.square(prediction - y))

# 使用交叉熵代价函数
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=y, logits=prediction))
# 使用梯度下降法
train_step = tf.train.GradientDescentOptimizer(0.1).minimize(loss)

# 初始化变量
init = tf.global_variables_initializer()

# 结果存放在一个布尔型的列表中
# 正确与否的True or False的列表
# tf.argmax返回一维张量中最大的值所在的索引位置
correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(prediction, 1))

# 求准确率
# 通过tf.cast(x, dtype)将布尔型转换为浮点型
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(201):
        for batch in range(n_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            sess.run(train_step, feed_dict={x: batch_xs, y: batch_ys})
        if epoch % 50 == 0:
            acc = sess.run(accuracy,feed_dict={x:mnist.test.images,y:mnist.test.labels})
            print("Iter " + str(epoch) + ",Testing Accuracy " + str(acc))



Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/train-images-idx3-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/train-labels-idx1-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/t10k-images-idx3-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/t10k-labels-idx1-ubyte.gz
Iter 0,Testing Accuracy 0.4171
Iter 50,Testing Accuracy 0.9053
Iter 100,Testing Accuracy 0.911
Iter 150,Testing Accuracy 0.9148
Iter 200,Testing Accuracy 0.9174


----

将batch_size从100改成50，loss函数使用交叉熵，并增加迭代次数，迭代次数从20到200.
+ 调整W和b的参数初始化方式
+ 添加一层隐藏层256个神经元，激活函数是tanh
+ 调整learning_rate为0.1
+ 调整优化器为AdamOptimizer

In [19]:
import os
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

# 载入数据集
mnist = input_data.read_data_sets(os.path.join(os.getcwd(), 'MNIST_data'), one_hot=True)

# 定义每个批次的大小
batch_size = 50
# 计算一共有多少个批次
n_batch = mnist.train.num_examples // batch_size  # 55000//100=550

# 定义两个placeholder
x = tf.placeholder(tf.float32, [None, 784])
y = tf.placeholder(tf.float32, [None, 10])

# 创建一个简单的神经网络
W1 = tf.Variable(tf.truncated_normal([784, 256]))
b1 = tf.Variable(tf.zeros([256]) + 0.1)
L1_output = tf.nn.tanh(tf.matmul(x, W1) + b1)

W2 = tf.Variable(tf.truncated_normal([256, 10]))
b2 = tf.Variable(tf.zeros([10]) + 0.1)
prediction = tf.nn.softmax(tf.matmul(L1_output, W2) + b2)

# 二次代价函数
# loss = tf.reduce_mean(tf.square(prediction - y))

# 使用交叉熵代价函数
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=y, logits=prediction))
# 使用梯度下降法
train_step = tf.train.AdamOptimizer(1e-4).minimize(loss)

# 初始化变量
init = tf.global_variables_initializer()

# 结果存放在一个布尔型的列表中
# 正确与否的True or False的列表
# tf.argmax返回一维张量中最大的值所在的索引位置
correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(prediction, 1))

# 求准确率
# 通过tf.cast(x, dtype)将布尔型转换为浮点型
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(201):
        for batch in range(n_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            sess.run(train_step, feed_dict={x: batch_xs, y: batch_ys})
        if epoch % 50 == 0:
            acc = sess.run(accuracy,feed_dict={x:mnist.test.images,y:mnist.test.labels})
            print("Iter " + str(epoch) + ",Testing Accuracy " + str(acc))





Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/train-images-idx3-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/train-labels-idx1-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/t10k-images-idx3-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/t10k-labels-idx1-ubyte.gz
Iter 0,Testing Accuracy 0.2989
Iter 50,Testing Accuracy 0.9121
Iter 100,Testing Accuracy 0.9299
Iter 150,Testing Accuracy 0.9351
Iter 200,Testing Accuracy 0.9392


将batch_size从100改成50，loss函数使用交叉熵，并增加迭代次数，迭代次数从20到200.
+ 调整W和b的参数初始化方式
+ 添加一层隐藏层256个神经元，激活函数是tanh
+ 调整learning_rate为0.1
+ 调整优化器为AdamOptimizer
+ 增加迭代次数到2000

In [20]:
import os
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

# 载入数据集
mnist = input_data.read_data_sets(os.path.join(os.getcwd(), 'MNIST_data'), one_hot=True)

# 定义每个批次的大小
batch_size = 50
# 计算一共有多少个批次
n_batch = mnist.train.num_examples // batch_size  # 55000//100=550

# 定义两个placeholder
x = tf.placeholder(tf.float32, [None, 784])
y = tf.placeholder(tf.float32, [None, 10])

# 创建一个简单的神经网络
W1 = tf.Variable(tf.truncated_normal([784, 256]))
b1 = tf.Variable(tf.zeros([256]) + 0.1)
L1_output = tf.nn.tanh(tf.matmul(x, W1) + b1)

W2 = tf.Variable(tf.truncated_normal([256, 10]))
b2 = tf.Variable(tf.zeros([10]) + 0.1)
prediction = tf.nn.softmax(tf.matmul(L1_output, W2) + b2)

# 二次代价函数
# loss = tf.reduce_mean(tf.square(prediction - y))

# 使用交叉熵代价函数
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=y, logits=prediction))
# 使用梯度下降法
train_step = tf.train.AdamOptimizer(1e-4).minimize(loss)

# 初始化变量
init = tf.global_variables_initializer()

# 结果存放在一个布尔型的列表中
# 正确与否的True or False的列表
# tf.argmax返回一维张量中最大的值所在的索引位置
correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(prediction, 1))

# 求准确率
# 通过tf.cast(x, dtype)将布尔型转换为浮点型
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(2001):
        for batch in range(n_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            sess.run(train_step, feed_dict={x: batch_xs, y: batch_ys})
        if epoch % 200 == 0:
            acc = sess.run(accuracy,feed_dict={x:mnist.test.images,y:mnist.test.labels})
            print("Iter " + str(epoch) + ",Testing Accuracy " + str(acc))



Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/train-images-idx3-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/train-labels-idx1-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/t10k-images-idx3-ubyte.gz
Extracting /Users/zoe/Documents/GitHub/July-NLP/TF/DATAGURU/Lec 03/MNIST_data/t10k-labels-idx1-ubyte.gz
Iter 0,Testing Accuracy 0.2748
Iter 200,Testing Accuracy 0.825
Iter 400,Testing Accuracy 0.9457
Iter 600,Testing Accuracy 0.9475
Iter 800,Testing Accuracy 0.9488
Iter 1000,Testing Accuracy 0.9497
Iter 1200,Testing Accuracy 0.9509
Iter 1400,Testing Accuracy 0.9524
Iter 1600,Testing Accuracy 0.9524
Iter 1800,Testing Accuracy 0.953
Iter 2000,Testing Accuracy 0.952


-----

tf.argmax就是返回最大的那个数值所在的下标。 

tf.argmax(array, 1)和tf.argmax(array, 0)有啥区别呢？    
    这里面就涉及到一个概念：axis。   
    上面例子中的1和0就是axis。

In [7]:
import numpy as np

test = np.array([[1, 2, 3], [2, 3, 4], [5, 4, 3], [8, 7, 2]])

print(test)
print(np.argmax(test, 0))
print(np.argmax(test, 1))

[[1 2 3]
 [2 3 4]
 [5 4 3]
 [8 7 2]]
[3 3 1]
[2 2 0 0]


tf.cast(x, dtype, name=None)    
将x的数据格式转化成dtype.   
例如，原来x的数据格式是bool，那么将其转化成float以后，就能够将其转化成0和1的序列。  
反之也可以。 

In [8]:
a = tf.Variable([1,0,0,1,1])
b = tf.cast(a, dtype=tf.bool)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(b))
    #[ True False False  True  True]

[ True False False  True  True]


---